application: bsafe4
version: 1
runtime: python
api_version: 1

handlers:

- url: /(.*\.(js|gif|png|jpg|css|ico))
  static_files: static/\1
  upload: static/(.*\.(js|gif|png|jpg|css))

- url: /
  static_files: static/kemege2.gif
  upload: static/kemege2.gif

- url: /main
  script: ImageViewer.py

- url: /upload
  script: Upload.py

- url: /image
  script: Img.py

- url: /thumb
  script: Thumb.py

- url: /clean
  login: admin
  script: clean.py

- url: /uploadtest
  static_files: static/upload.html
  upload: static/upload.html

