application: 75bnin
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:

- url: /(.*\.(js|gif|png|jpg|css|ico))
  static_files: static/\1
  upload: static/(.*\.(js|gif|png|jpg|css|ico))

- url: /
  script: Index.py

- url: /list
  script: List.py

- url: /info
  script: Info.py

- url: /upload.*
  script: Upload.py

- url: /data
  script: DataServe.py

- url: /uploadpage
  static_files: static/upload.html
  upload: static/upload.html

- url: /edit.*
  script: Edit.py

- url: /show.*
  script: ShowSimple.py

- url: /search
  script: Search.py

- url: /add.*
  script: Add.py

- url: /main
  script: Main.py

- url: /stat.*
  script: Statistics.py

- url: /maintain.*
  script: Maintain.py

libraries:
- name: django
  version: latest