application: 75bnin
version: 1
runtime: python
api_version: 1

handlers:

- url: /(.*\.(js|gif|png|jpg|css|ico))
  static_files: static/\1
  upload: static/(.*\.(js|gif|png|jpg|css))

- url: /
  static_files: static/index.gif
  upload: static/index.gif

- url: /list
  script: List.py

- url: /info
  script: Info.py

- url: /upload
  script: Upload.py

- url: /upload/bin
  script: UploadBinary.py

- url: /upload/simple
  script: UploadSimple.py

- url: /data
  script: DataServe.py

- url: /uploadpage
  static_files: static/upload.html
  upload: static/upload.html

- url: /edit
  script: EditText.py

- url: /editlink
  script: EditLink.py

- url: /search
  script: Search.py

- url: /adds
  script: AddSeiyuu.py

- url: /addc
  script: AddChara.py